//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileStore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001,Bulbasaur,,Grass,Poison
        ///002,Ivysaur,,Grass,Poison
        ///003,Venusaur,,Grass,Poison
        ///003,Venusaur,Mega Venusaur,Grass,Poison
        ///004,Charmander,,Fire,
        ///005,Charmeleon,,Fire,
        ///006,Charizard,,Fire,Flying
        ///006,Charizard,Mega Charizard X,Fire,Dragon
        ///006,Charizard,Mega Charizard Y,Fire,Flying
        ///007,Squirtle,,Water,
        ///008,Wartortle,,Water,
        ///009,Blastoise,,Water,
        ///009,Blastoise,Mega Blastoise,Water,
        ///010,Caterpie,,Bug,
        ///011,Metapod,,Bug,
        ///012,Butterfree,,Bug,Flying
        ///013,Weedle,,Bug,Poison
        ///014,Kakuna,,Bug,Poison
        ///015,B [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pokedexAll {
            get {
                return ResourceManager.GetString("pokedexAll", resourceCulture);
            }
        }
    }
}
