//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileStore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001,Bulbasaur,
        ///002,Ivysaur,
        ///003,Venusaur,
        ///003,Venusaur,Mega Venusaur
        ///004,Charmander,
        ///005,Charmeleon,
        ///006,Charizard,
        ///006,Charizard,Mega Charizard X
        ///006,Charizard,Mega Charizard Y
        ///007,Squirtle,
        ///008,Wartortle,
        ///009,Blastoise,
        ///009,Blastoise,Mega Blastoise
        ///010,Caterpie,
        ///011,Metapod,
        ///012,Butterfree,
        ///013,Weedle,
        ///014,Kakuna,
        ///015,Beedrill,
        ///015,Beedrill,Mega Beedrill
        ///016,Pidgey,
        ///017,Pidgeotto,
        ///018,Pidgeot,
        ///018,Pidgeot,Mega Pidgeot
        ///019,Rattata,
        ///019,Rattata,Alolan Rattata
        ///020,Raticate,
        ///020,Rat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pokedexAll {
            get {
                return ResourceManager.GetString("pokedexAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Bug {
            get {
                object obj = ResourceManager.GetObject("Type_Bug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Dark {
            get {
                object obj = ResourceManager.GetObject("Type_Dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Dragon {
            get {
                object obj = ResourceManager.GetObject("Type_Dragon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Electric {
            get {
                object obj = ResourceManager.GetObject("Type_Electric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Fairy {
            get {
                object obj = ResourceManager.GetObject("Type_Fairy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Fighting {
            get {
                object obj = ResourceManager.GetObject("Type_Fighting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Fire {
            get {
                object obj = ResourceManager.GetObject("Type_Fire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Flying {
            get {
                object obj = ResourceManager.GetObject("Type_Flying", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Ghost {
            get {
                object obj = ResourceManager.GetObject("Type_Ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Grass {
            get {
                object obj = ResourceManager.GetObject("Type_Grass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Ground {
            get {
                object obj = ResourceManager.GetObject("Type_Ground", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Ice {
            get {
                object obj = ResourceManager.GetObject("Type_Ice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Normal {
            get {
                object obj = ResourceManager.GetObject("Type_Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Poison {
            get {
                object obj = ResourceManager.GetObject("Type_Poison", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Psychic {
            get {
                object obj = ResourceManager.GetObject("Type_Psychic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Rock {
            get {
                object obj = ResourceManager.GetObject("Type_Rock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Steel {
            get {
                object obj = ResourceManager.GetObject("Type_Steel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Type_Water {
            get {
                object obj = ResourceManager.GetObject("Type_Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
