#!/usr/bin/env python3
"""Regenerates PokemonDataModel/PastStatsTable.cs from PokeAPI's own source CSV.

Usage:
    python Tools/generate_past_stats_table.py > PokemonDataModel/PastStatsTable.cs

Source data: PokeAPI/pokeapi's data/v2/csv/pokemon_stats_past.csv - the sparse historical stat
deltas the live API's `past_stats` field is generated from. Re-run this whenever PokeAPI adds a
new generation's worth of stat history (e.g. a future generation's rebalance) and diff the result.
"""

import csv
import io
import sys
import urllib.request

CSV_URL = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_stats_past.csv"

# From PokeAPI's data/v2/csv/stats.csv - stable, hasn't changed since Gen 1's "special" stat (id 9)
# was added to the schema.
STAT_NAMES = {
    "1": "hp",
    "2": "attack",
    "3": "defense",
    "4": "special-attack",
    "5": "special-defense",
    "6": "speed",
    "9": "special",
}


def fetch_rows():
    with urllib.request.urlopen(CSV_URL) as response:
        text = response.read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(text)))


def group_by_pokemon(rows):
    by_pokemon = {}
    for row in rows:
        pid = int(row["pokemon_id"])
        gen = int(row["generation_id"])
        stat = STAT_NAMES[row["stat_id"]]
        by_pokemon.setdefault(pid, {}).setdefault(gen, {})[stat] = int(row["base_stat"])
    return by_pokemon


def render(by_pokemon):
    lines = []
    lines.append("// <auto-generated>")
    lines.append("// Generated by Tools/generate_past_stats_table.py from PokeAPI/pokeapi's")
    lines.append(f"// data/v2/csv/pokemon_stats_past.csv. Do not edit by hand - re-run the script instead.")
    lines.append("//")
    lines.append("// Each entry's Generation is the LAST generation in which the pokemon had the listed base")
    lines.append("// stats (matching PastTypes' convention) - the change to current-day values took effect the")
    lines.append("// generation after. \"special\" (Gen 1's combined Sp.Atk/Sp.Def stat) is a distinct key from")
    lines.append("// \"special-attack\"/\"special-defense\" here; SmartPokemon.GetStatsForGeneration collapses it.")
    lines.append("// </auto-generated>")
    lines.append("namespace PokemonDataModel")
    lines.append("{")
    lines.append("    // A pokemon's historical base stat deltas, keyed by PokeAPI pokemon id (matches SmartPokemon.Id,")
    lines.append("    // including form varieties like Mega Alakazam's own id). Only pokemon whose stats have ever")
    lines.append("    // changed appear here - see SmartPokemon.GetStatsForGeneration for how an absent id or an absent")
    lines.append("    // qualifying entry is handled.")
    lines.append("    public static class PastStatsTable")
    lines.append("    {")
    lines.append("        public static readonly IReadOnlyDictionary<int, IReadOnlyList<PastStatsEntry>> ByPokemonId =")
    lines.append("            new Dictionary<int, IReadOnlyList<PastStatsEntry>>")
    lines.append("            {")

    for pid in sorted(by_pokemon.keys()):
        gens = by_pokemon[pid]
        entries = []
        for gen in sorted(gens.keys()):
            stats = gens[gen]
            stat_str = ", ".join(f'["{k}"] = {v}' for k, v in stats.items())
            entries.append(f"new PastStatsEntry({gen}, new Dictionary<string, int> {{ {stat_str} }})")
        entries_str = ", ".join(entries)
        lines.append(f"                [{pid}] = [{entries_str}],")

    lines.append("            };")
    lines.append("    }")
    lines.append("")
    lines.append("    // One historical stat delta: the base stats that applied through (and including) Generation,")
    lines.append("    // for whichever stats changed at that point - not a full stat line, only the ones that differ")
    lines.append("    // from the current-day values shown by SmartPokemon.Stats.")
    lines.append("    public sealed record PastStatsEntry(int Generation, IReadOnlyDictionary<string, int> Stats);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    rows = fetch_rows()
    by_pokemon = group_by_pokemon(rows)
    sys.stdout.write(render(by_pokemon))


if __name__ == "__main__":
    main()
